name: Unashamedly You
favicon: null
layout_spectrum: 0.23749307449907064
typography_spectrum: 0.7638179955538362
title: Unashamedly You
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fafd'
    - '#bfded9'
    - '#e1e9dc'
    - '#baedf8'
    - '#7bc8c6'
  brandStrength: 0.15179640497080982
  lightness: 0.9526607987936586
  saturation: 0.8519014266785234
  rhythmicContrast: 0.0012971952091902494
purpose: []
